// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYJS2CTlCGWx4Xtd8BPG2XrYPxFTGRINk',
    appId: '1:836132321200:web:d261dd103b81b68cb48875',
    messagingSenderId: '836132321200',
    projectId: 'attendance-app-peny-2026-e309c',
    authDomain: 'attendance-app-peny-2026-e309c.firebaseapp.com',
    storageBucket: 'attendance-app-peny-2026-e309c.firebasestorage.app',
    measurementId: 'G-YKYV4996X0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3_RpsyK6rRBB5-OkR2f6WY0nzBPW9Qc',
    appId: '1:836132321200:ios:ce8ef7972a0c3632b48875',
    messagingSenderId: '836132321200',
    projectId: 'attendance-app-peny-2026-e309c',
    storageBucket: 'attendance-app-peny-2026-e309c.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl3_RpsyK6rRBB5-OkR2f6WY0nzBPW9Qc',
    appId: '1:836132321200:ios:ce8ef7972a0c3632b48875',
    messagingSenderId: '836132321200',
    projectId: 'attendance-app-peny-2026-e309c',
    storageBucket: 'attendance-app-peny-2026-e309c.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYJS2CTlCGWx4Xtd8BPG2XrYPxFTGRINk',
    appId: '1:836132321200:web:ad5de4205069f730b48875',
    messagingSenderId: '836132321200',
    projectId: 'attendance-app-peny-2026-e309c',
    authDomain: 'attendance-app-peny-2026-e309c.firebaseapp.com',
    storageBucket: 'attendance-app-peny-2026-e309c.firebasestorage.app',
    measurementId: 'G-LEK6LGRJ9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0JF-PGJSIoIEftE0vct_gwAUnlJiaQk',
    appId: '1:836132321200:android:4d9264fcb22b09e5b48875',
    messagingSenderId: '836132321200',
    projectId: 'attendance-app-peny-2026-e309c',
    storageBucket: 'attendance-app-peny-2026-e309c.firebasestorage.app',
  );

}